### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by zecoxao** [TitleOS/QuantumTunnel#9]
admin@XBOXONE D:\DevelopmentFiles>Dotnet6\dotnet.exe QuantumTunnel.dll -r -o dump.bin
QuantumTunnel - C# FlashFS Reader
Unhandled exception. System.UnauthorizedAccessException: Access to the path 'D:\DevelopmentFiles\dump.bin' is denied.

I have done this after successfully running Artifice. what is the issue here?

**Comment by PurpleVoidEpic** [comment]
you have to get a system shell maybe via https://xboxresearch.com/wiki/setup-dev-mode/#using-ssh

**Comment by PurpleVoidEpic** [comment]
oops

**Comment by PurpleVoidEpic** [comment]
hang on i think you run REG ADD HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Bootsh\Parameters\Commands /v Xrun /t REG_SZ /d "telnetd.exe cmd.exe 23" /f
sc start bootsh then REG ADD HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Bootsh\Parameters\Commands /v Xrun /t REG_SZ /d "xrun.exe SystemBootTasks" /f then telnet at port 23

**Comment by zecoxao** [comment]
i do all this in admin account?

**Comment by zecoxao** [comment]
i tried and it still didn't work

**Comment by Kudayasu** [comment]
The absolute easiest route is to use the publish option in Visual Studio.
![ZKZAm2GyI9](https://github.com/TitleOS/QuantumTunnel/assets/17820526/44b88107-45f4-4208-b60a-d6d89b0f9006)
![cmd_p78NaQm7op](https://github.com/TitleOS/QuantumTunnel/assets/17820526/dbabdf60-d4a1-4eb6-90ba-4e0995f259b9)

That way, you won't have to mess with any environment variables.

PurpleVoid is correct, and the [prerequisites](https://github.com/TitleOS/QuantumTunnel#prerequisites) mention this, you need to elevate to a **SYSTEM** shell in order to access the flash. 

So, in your admin ssh shell:
`REG ADD HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Bootsh\Parameters\Commands /v Xrun /t REG_SZ /d "telnetd.exe cmd.exe 23"`
`sc start bootsh`

Then on your desktop, `telnet {Hostname|IP} 23`

If you don't have telnet enabled, follow the guide [here](https://phoenixnap.com/kb/telnet-windows#option-1-enable-telnet-using-gui)

`D:\DevelopmentFiles\QuantumTunnel.exe {operation}`

**Comment by zecoxao** [comment]
Thanks Kudayasu for having given me the proper explanation. the publish option was the missing link :)

**Comment by zecoxao** [comment]
You guys may close this, it works properly now
